[package]
name = "broadcast-channel"
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/broadcast-channel"
documentation = "https://docs.rs/broadcast-channel"
description = "Async broadcast channels"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Stjepan Glavina <stjepang@gmail.com>",
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
    "Zeeshan Ali <zeeshanak@gnome.org>",
]

[features]

[dependencies]
async-mutex = "1.3.0"
event-listener = "2.5.1"
futures-core = "0.3.14"

[dev-dependencies]
futures-util = "0.3.14"
pollster = "0.2.4"
