[package]
name = "broadcast-channel"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/broadcast-channel"
documentation = "https://docs.rs/broadcast-channel"
description = "Async broadcast channels"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>"
]

[features]

[dependencies]
async-mutex = "1.3.0"

[dev-dependencies]
